name: Security Audit

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Run cargo audit
        run: |
          cargo install cargo-audit --locked
          cargo audit --args "--ignore RUSTSEC-2020-0071 --ignore RUSTSEC-2021-0062 --ignore RUSTSEC-2022-0004"
        env:
          RUSTSEC_CHECK_SKIP_UNMAINTAINED: 1